"""changed the datetime to include timezones.

Revision ID: 077abaa0a13c
Revises: 39018a8c3010
Create Date: 2023-06-06 08:51:56.631535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077abaa0a13c'
down_revision = '39018a8c3010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
