"""changed schema for reservations

Revision ID: 10e4e2814e0f
Revises: a36211589b7d
Create Date: 2023-06-07 09:40:17.574473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10e4e2814e0f'
down_revision = 'a36211589b7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('reservations', sa.Column('total_amount', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('reference_no', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('guest_data', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('reservations', sa.Column('reservation_data', sa.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('reservations', 'selected_accomodations')
    op.drop_column('reservations', 'guest_entrace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('guest_entrace', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('selected_accomodations', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('reservations', 'reservation_data')
    op.drop_column('reservations', 'guest_data')
    op.drop_column('reservations', 'reference_no')
    op.drop_column('reservations', 'total_amount')
    # ### end Alembic commands ###
