"""changed schema for reservations.

Revision ID: 28f36eb93636
Revises: 6d1cd6a01a51
Create Date: 2023-06-06 09:59:30.415489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f36eb93636'
down_revision = '6d1cd6a01a51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entrace_fees_name'), 'entrace_fees', ['name'], unique=True)
    op.add_column('reservations', sa.Column('extras', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'extras')
    op.drop_index(op.f('ix_entrace_fees_name'), table_name='entrace_fees')
    # ### end Alembic commands ###
