"""changed schema for accomodations.

Revision ID: 3437442b829a
Revises: 85ac0307709d
Create Date: 2023-06-06 09:21:12.003342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3437442b829a'
down_revision = '85ac0307709d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accomodations', sa.Column('whole_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accomodations', 'whole_day')
    # ### end Alembic commands ###
