"""change schema for tables reservation.

Revision ID: 356fba9adf51
Revises: 97f93352eef0
Create Date: 2023-06-07 15:35:56.784813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356fba9adf51'
down_revision = '97f93352eef0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('selected_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'selected_time')
    # ### end Alembic commands ###
