"""added all possible tables.

Revision ID: 39018a8c3010
Revises: bff65882a22a
Create Date: 2023-06-06 08:50:29.073145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39018a8c3010'
down_revision = 'bff65882a22a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
