"""added refund amount field in reservation cancellation request.

Revision ID: 44cf50f9a66a
Revises: cb568cf42ff7
Create Date: 2023-06-10 20:20:21.131549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cf50f9a66a'
down_revision = 'cb568cf42ff7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
