"""added address field to the reservations.

Revision ID: 44f40d895569
Revises: 44cf50f9a66a
Create Date: 2023-06-13 15:57:43.572272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f40d895569'
down_revision = '44cf50f9a66a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'address')
    # ### end Alembic commands ###
