"""added new tables for reviews, comments, and reservation cancellation request.

Revision ID: 50f96270aa53
Revises: 30ae9deebed4
Create Date: 2023-06-08 18:41:11.873155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f96270aa53'
down_revision = '30ae9deebed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
