"""changed table for reservation

Revision ID: 590f7fd115e8
Revises: b375876e737c
Create Date: 2023-06-07 14:44:17.447516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590f7fd115e8'
down_revision = 'b375876e737c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
