"""changed schema for entrace fees.

Revision ID: 6d1cd6a01a51
Revises: 3437442b829a
Create Date: 2023-06-06 09:25:07.816442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1cd6a01a51'
down_revision = '3437442b829a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrace_fees', sa.Column('whole_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrace_fees', 'whole_day')
    # ### end Alembic commands ###
