"""changed schema for reservations

Revision ID: 70f498c63854
Revises: fe546060c2f1
Create Date: 2023-06-06 22:49:42.375078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70f498c63854'
down_revision = 'fe546060c2f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('guest_entrace', sa.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('reservations', 'quest_entrace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('quest_entrace', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('reservations', 'guest_entrace')
    # ### end Alembic commands ###
