"""changed schema for packages.

Revision ID: 85ac0307709d
Revises: 077abaa0a13c
Create Date: 2023-06-06 09:19:41.646812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ac0307709d'
down_revision = '077abaa0a13c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('whole_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'whole_day')
    # ### end Alembic commands ###
