"""changed table for package

Revision ID: 87a9228cbb22
Revises: 8be4c2baf7f8
Create Date: 2023-06-07 12:09:31.663431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a9228cbb22'
down_revision = '8be4c2baf7f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('plans', sa.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('packages', 'end_time')
    op.drop_column('packages', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('packages', sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('packages', 'plans')
    # ### end Alembic commands ###
