"""changed schema for making packages

Revision ID: a36211589b7d
Revises: 70f498c63854
Create Date: 2023-06-07 08:59:09.539430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36211589b7d'
down_revision = '70f498c63854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('day_time', sa.String(), nullable=True))
    op.add_column('packages', sa.Column('night_time', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('payment', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('total_amount', sa.Integer(), nullable=True))
    op.drop_column('reservations', 'total_payment')
    op.drop_column('reservations', 'initial_payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('initial_payment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('total_payment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('reservations', 'total_amount')
    op.drop_column('reservations', 'payment')
    op.drop_column('packages', 'night_time')
    op.drop_column('packages', 'day_time')
    # ### end Alembic commands ###
