"""changed table for package

Revision ID: b375876e737c
Revises: 87a9228cbb22
Create Date: 2023-06-07 12:19:16.432221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b375876e737c'
down_revision = '87a9228cbb22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'name')
    # ### end Alembic commands ###
