"""added packages table.

Revision ID: bff65882a22a
Revises: 0f66daf98834
Create Date: 2023-06-05 18:26:36.419872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff65882a22a'
down_revision = '0f66daf98834'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
