"""added refund amount field in reservation cancellation request.

Revision ID: cb568cf42ff7
Revises: 28e5b492322a
Create Date: 2023-06-10 20:17:04.933215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb568cf42ff7'
down_revision = '28e5b492322a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
