"""changed schema for accomodations.

Revision ID: fe546060c2f1
Revises: 28f36eb93636
Create Date: 2023-06-06 11:09:49.609668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe546060c2f1'
down_revision = '28f36eb93636'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
